variables:
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  
stages:
  - test

.common:
  tags_template: &tags
    tags:
     - 
     
image: 

cache:
  paths:
    - .m2/repository

test:
  stage: test
  artifacts:
    when: on_failure
    name: "$CI_COMMIT_REF_NAME"
    paths:
      - target/cucumber-reports/
  allow_failure: true
  script:
    - mvn $MAVEN_CLI_OPTS test -Dcucumber.options="--tags '@dmgAssignment'"
